import PDFDocument from "pdfkit";
import Prescription from "../../models/doctors/Prescription.js";

export const createPrescription = async (req, res) => {
  try {
    const prescription = await Prescription.create({
      doctor: req.doctor.id,
      ...req.body,
    });

    res.json({
      success: true,
      message: "Prescription created",
      data: prescription,
    });
  } catch (error) {
    console.error("Create prescription error:", error);
    res.status(500).json({ message: "Failed to create prescription" });
  }
};

export const getPrescriptions = async (req, res) => {
  try {
    const prescriptions = await Prescription.find({
      doctor: req.doctor.id,
    }).sort({ createdAt: -1 });

    res.json({
      success: true,
      data: prescriptions,
    });
  } catch (error) {
    res.status(500).json({ message: "Failed to fetch prescriptions" });
  }
};


export const downloadPrescriptionPDF = async (req, res) => {
  try {
    const prescription = await Prescription.findOne({
      _id: req.params.id,
      doctor: req.doctor.id,
    });

    if (!prescription) {
      return res.status(404).json({ message: "Prescription not found" });
    }

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=prescription-${prescription._id}.pdf`
    );

    doc.pipe(res);

    doc
      .fontSize(20)
      .text("BioBurg Health", { align: "center" })
      .moveDown(0.5);

    doc
      .fontSize(12)
      .text("Doctor Prescription", { align: "center" })
      .moveDown(1);

    doc.fontSize(12);
    doc.text(`Patient Name: ${prescription.patientName}`);
    doc.text(`Age: ${prescription.patientAge || "-"}`);
    doc.text(`Gender: ${prescription.patientGender || "-"}`);
    doc.moveDown();

    doc.fontSize(13).text("Diagnosis:", { underline: true });
    doc.fontSize(12).text(prescription.diagnosis || "-");
    doc.moveDown();

    doc.fontSize(13).text("Medicines:", { underline: true });
    doc.moveDown(0.5);

    prescription.medicines.forEach((m, i) => {
      doc.text(
        `${i + 1}. ${m.name} | ${m.dosage} | ${m.duration}`
      );
    });

    doc.moveDown();

    if (prescription.notes) {
      doc.fontSize(13).text("Notes:", { underline: true });
      doc.fontSize(12).text(prescription.notes);
      doc.moveDown();
    }

    doc
      .moveDown(2)
      .fontSize(10)
      .text("Generated by BioBurg Life Science", {
        align: "center",
      });

    doc.end();
  } catch (error) {
    console.error("PDF error:", error);
    res.status(500).json({ message: "Failed to generate PDF" });
  }
};